config/routes.rb
Apparts::Application.routes.draw do
  resources :appartments do
    get 'like'
  end

  root :to => "appartments#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/appartment.rb
class Appartment
  include Mongoid::Document
  field :city, :type => String
  field :note, :type => Integer
  field :price, :type => Integer
  field :square_meters, :type => Integer
  field :tax, :type => Integer
  field :charges, :type => Integer
  field :ecoclass, :type => String
  field :geographic_location, :type => String
  field :kitchen, :type => String
  field :condition, :type => String
  field :area, :type => String
  field :contact, :type => String
  field :seen, :type => String
  field :link, :type => String
  field :like, :type => Boolean
end

app/controllers/appartments_controller.rb
class AppartmentsController < ApplicationController
  # GET /appartments
  # GET /appartments.xml
  def index
    @appartments = Appartment.all.desc(:like, :note).asc(:city)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @appartments }
    end
  end

  # GET /appartments/1
  # GET /appartments/1.xml
  def show
    @appartment = Appartment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @appartment }
    end
  end

  # GET /appartments/new
  # GET /appartments/new.xml
  def new
    @appartment = Appartment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @appartment }
    end
  end

  # GET /appartments/1/edit
  def edit
    @appartment = Appartment.find(params[:id])
  end

  # POST /appartments
  # POST /appartments.xml
  def create
    @appartment = Appartment.new(params[:appartment])

    respond_to do |format|
      if @appartment.save
        format.html { redirect_to(@appartment, :notice => 'Appartment was successfully created.') }
        format.xml  { render :xml => @appartment, :status => :created, :location => @appartment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @appartment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /appartments/1
  # PUT /appartments/1.xml
  def update
    @appartment = Appartment.find(params[:id])

#    if not params[:like].nil?
#      if @appartment.like==true
#      then
#        @appartment.like = false
#      else
#        @appartment.like = true
#      end
#      @appartment.save
#      respond_to do |format|
#        format.html { redirect_to(appartments_url) }
#        format.xml  { head :ok }
#      end
#    end

    respond_to do |format|
      if @appartment.update_attributes(params[:appartment])
        format.html { redirect_to(@appartment, :notice => 'Appartment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @appartment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /appartments/1
  # DELETE /appartments/1.xml
  def destroy
    @appartment = Appartment.find(params[:id])
    @appartment.destroy

    respond_to do |format|
      format.html { redirect_to(appartments_url) }
      format.xml  { head :ok }
    end
  end

  def like
    @appartment = Appartment.find(params[:id])
    if @appartment.like
    then
      @appartment.like = false
    else
      @appartment.like = true
    end
    @appartment.save
    respond_to do |format|
      format.html { redirect_to(appartments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/appartments_helper.rb
module AppartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appartments/_form.html.erb
<%= form_for(@appartment) do |f| %>
  <% if @appartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appartment.errors.count, "error") %> prohibited this appartment from being saved:</h2>

      <ul>
      <% @appartment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :square_meters %><br />
    <%= f.text_field :square_meters %>
  </div>
  <div class="field">
    <%= f.label :tax %><br />
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :charges %><br />
    <%= f.text_field :charges %>
  </div>
  <div class="field">
    <%= f.label :ecoclass %><br />
    <%= f.text_field :ecoclass %>
  </div>
  <div class="field">
    <%= f.label :geographic_location %><br />
    <%= f.text_area :geographic_location %>
  </div>
  <div class="field">
    <%= f.label :kitchen %><br />
    <%= f.text_area :kitchen %>
  </div>
  <div class="field">
    <%= f.label :condition %><br />
    <%= f.text_area :condition %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_area :area %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_area :contact %>
  </div>
  <div class="field">
    <%= f.label :seen %><br />
    <%= f.text_area :seen %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appartments/edit.html.erb
<h1>Editing appartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appartment %> |
<%= link_to 'Back', appartments_path %>

app/views/appartments/index.html.erb
<h1>Listing appartements</h1>
<%= link_to 'Ajouter un appartement', new_appartment_path %>

<table width="2048">
  <tr>
    <th>Note</th>
    <th>Ville</th>
    <th>Prix</th>
    <th>m²</th>
    <th>prix/m²</th>
    <th>Prix avec notaire</th>
    <th>Taxe fonciere</th>
    <th>Charges</th>
    <th>Classe ecologique</th>
    <th>Situation geographique</th>
    <th>Cuisine</th>
    <th>Etat</th>
    <th>Quartier</th>
    <th>Contact</th>
    <th>Visite</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appartments.each do |appartment| %>
  <tr<% if appartment.like==true then %> bgcolor="#A9EAFF"<% end %>>
    <td><%= appartment.note %></td>
    <td><%= appartment.city %></td>
    <td><%= appartment.price %></td>
    <td><%= appartment.square_meters %></td>
    <td><%= (appartment.price.to_i/appartment.square_meters.to_i).to_s if appartment.square_meters.to_i > 0 %></td>
    <td><%= (appartment.price+appartment.price*0.1).to_i %></td>
    <td><%= appartment.tax %></td>
    <td><%= appartment.charges %></td>
    <td><%= appartment.ecoclass %></td>
    <td><%= appartment.geographic_location %></td>
    <td><%= appartment.kitchen %></td>
    <td><%= appartment.condition %></td>
    <td><%= appartment.area %></td>
    <td><%= appartment.contact %></td>
    <td><%= appartment.seen %></td>
    <td><%= link_to 'Like / Unlike', :action => 'like', :id => appartment %></td>
    <td><%= link_to 'Lien', appartment.link %></td>
    <td><%= link_to 'Voir', appartment %></td>
    <td><%= link_to 'Modifier', edit_appartment_path(appartment) %></td>
    <td><%= link_to 'Supprimer', appartment, :confirm => 'Etes vous sur?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Ajouter un appartement', new_appartment_path %>

app/views/appartments/new.html.erb
<h1>New appartment</h1>

<%= render 'form' %>

<%= link_to 'Back', appartments_path %>

app/views/appartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ville:</b>
  <%= @appartment.city %>
</p>

<p>
  <b>Prix:</b>
  <%= @appartment.price %>
</p>

<p>
  <b>m²:</b>
  <%= @appartment.square_meters %>
</p>

<p>
  <b>Taxe fonciere:</b>
  <%= @appartment.tax %>
</p>

<p>
  <b>Charges:</b>
  <%= @appartment.charges %>
</p>

<p>
  <b>Classe ecologique:</b>
  <%= @appartment.ecoclass %>
</p>

<p>
  <b>Situation geographique:</b>
  <%= @appartment.geographic_location %>
</p>

<p>
  <b>Cuisine:</b>
  <%= @appartment.kitchen %>
</p>

<p>
  <b>Etat:</b>
  <%= @appartment.condition %>
</p>

<p>
  <b>Quartier:</b>
  <%= @appartment.area %>
</p>

<p>
  <b>Contact:</b>
  <%= @appartment.contact %>
</p>

<p>
  <b>Visite:</b>
  <%= @appartment.seen %>
</p>

<p>
  <b>Lien:</b>
  <%= link_to @appartment.link, @appartment.link %>
</p>


<%= link_to 'Modifier', edit_appartment_path(@appartment) %> |
<%= link_to 'Retour', appartments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apparts</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>